-- Insert 50 fake job posts with skill requirements for Nepal market
-- These jobs use the tag-based skill requirements system (comma-separated format)

INSERT INTO opportunities (title, description, type, organizer_id, location, salary_range, contact_email, application_deadline, requirements, is_active, date_posted) VALUES

-- Web Development Jobs (10)
('Frontend Developer - React Specialist', 'Looking for an experienced React developer to join our team. Work on cutting-edge web applications using modern JavaScript frameworks. Remote work available.', 'employment', 3, 'Kathmandu, Nepal', 'NPR 50,000 - 80,000', 'jobs@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 30 DAY), 'React, JavaScript, HTML, CSS, Git, REST API, Responsive Design', TRUE, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('Full Stack Developer Intern', 'Exciting internship opportunity for fresh graduates passionate about web development. Learn from experienced developers while working on real projects.', 'internship', 4, 'Lalitpur, Nepal', 'NPR 15,000 - 25,000', 'internships@nepaltech.com', DATE_ADD(NOW(), INTERVAL 45 DAY), 'JavaScript, Node.js, MongoDB, HTML, CSS, Git, Express.js', TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY)),
('Backend Developer - Python/Django', 'Join our backend team to build scalable web services. Work with Python, Django, and PostgreSQL in a fast-paced startup environment.', 'employment', 3, 'Pokhara, Nepal', 'NPR 60,000 - 90,000', 'careers@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 30 DAY), 'Python, Django, PostgreSQL, REST API, Git, Linux, AWS', TRUE, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('Vue.js Developer', 'We are seeking a Vue.js developer to help build our client-facing applications. Knowledge of Vue 3 Composition API preferred.', 'employment', 5, 'Remote', 'NPR 45,000 - 70,000', 'hr@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 35 DAY), 'Vue.js, JavaScript, TypeScript, HTML, CSS, Git, REST API', TRUE, NOW()),
('MEAN Stack Developer', 'Full-time position for a MEAN stack developer. Build end-to-end web applications using MongoDB, Express, Angular, and Node.js.', 'employment', 4, 'Kathmandu, Nepal', 'NPR 55,000 - 85,000', 'jobs@nepaltech.com', DATE_ADD(NOW(), INTERVAL 40 DAY), 'Angular, Node.js, Express.js, MongoDB, JavaScript, TypeScript, Git', TRUE, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('WordPress Developer', 'Looking for a WordPress developer to customize themes and plugins for our client websites. Experience with PHP and WordPress required.', 'employment', 5, 'Kathmandu, Nepal', 'NPR 35,000 - 55,000', 'webdev@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 25 DAY), 'WordPress, PHP, HTML, CSS, JavaScript, MySQL, Git', TRUE, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('Laravel Developer Intern', 'Internship for students interested in PHP backend development. Learn Laravel framework while building real-world applications.', 'internship', 6, 'Lalitpur, Nepal', 'NPR 12,000 - 20,000', 'intern@demo.org', DATE_ADD(NOW(), INTERVAL 60 DAY), 'PHP, Laravel, MySQL, HTML, CSS, Git, REST API', TRUE, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('JavaScript Developer', 'Seeking a JavaScript developer with strong ES6+ knowledge. Work on frontend and backend JavaScript applications.', 'employment', 3, 'Remote', 'NPR 40,000 - 65,000', 'dev@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 30 DAY), 'JavaScript, Node.js, Express.js, Git, REST API, JSON', TRUE, DATE_SUB(NOW(), INTERVAL 6 DAY)),
('Next.js Developer', 'Join our team to build server-side rendered React applications using Next.js. Experience with SSR and SSG preferred.', 'employment', 4, 'Kathmandu, Nepal', 'NPR 55,000 - 80,000', 'nextjs@nepaltech.com', DATE_ADD(NOW(), INTERVAL 35 DAY), 'Next.js, React, TypeScript, JavaScript, CSS, Git, REST API', TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY)),
('Web Development Intern', 'Perfect opportunity for CS students to learn web development. Work on both frontend and backend projects with mentorship.', 'internship', 5, 'Pokhara, Nepal', 'NPR 10,000 - 18,000', 'webintern@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 50 DAY), 'HTML, CSS, JavaScript, Git, Basic Programming, Web Fundamentals', TRUE, NOW()),

-- Mobile Development Jobs (6)
('Flutter Developer', 'Looking for a Flutter developer to build cross-platform mobile applications. Experience with Dart and mobile UI/UX required.', 'employment', 3, 'Kathmandu, Nepal', 'NPR 50,000 - 75,000', 'mobile@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 30 DAY), 'Flutter, Dart, Firebase, REST API, Git, Mobile UI/UX', TRUE, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('React Native Developer', 'Join our mobile team to develop React Native applications for iOS and Android platforms.', 'employment', 4, 'Remote', 'NPR 48,000 - 72,000', 'reactnative@nepaltech.com', DATE_ADD(NOW(), INTERVAL 35 DAY), 'React Native, JavaScript, Redux, REST API, Git, Mobile Development', TRUE, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('Android Developer Intern', 'Internship for Android development enthusiasts. Build native Android apps using Java/Kotlin with guidance from senior developers.', 'internship', 6, 'Lalitpur, Nepal', 'NPR 15,000 - 22,000', 'android@demo.org', DATE_ADD(NOW(), INTERVAL 55 DAY), 'Android Development, Java, Kotlin, XML, Git, REST API', TRUE, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('iOS Developer', 'Seeking an iOS developer to create native iOS applications using Swift. Experience with SwiftUI preferred.', 'employment', 5, 'Kathmandu, Nepal', 'NPR 52,000 - 78,000', 'ios@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 32 DAY), 'iOS Development, Swift, SwiftUI, Xcode, Git, REST API', TRUE, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('Mobile App Developer', 'Full-stack mobile developer needed for hybrid app development. Experience with Ionic or React Native required.', 'employment', 3, 'Pokhara, Nepal', 'NPR 45,000 - 70,000', 'mobileapp@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 28 DAY), 'React Native, Ionic, JavaScript, REST API, Git, Mobile UI/UX', TRUE, NOW()),
('Mobile Development Intern', 'Learn mobile app development from scratch. Work on real mobile projects with mentorship support.', 'internship', 4, 'Kathmandu, Nepal', 'NPR 12,000 - 20,000', 'mobileintern@nepaltech.com', DATE_ADD(NOW(), INTERVAL 60 DAY), 'JavaScript, Basic Programming, Mobile Development, Git', TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY)),

-- Data Science & Analytics Jobs (6)
('Data Analyst', 'Analyze business data and create insights using Python, SQL, and data visualization tools. Help drive data-driven decisions.', 'employment', 5, 'Kathmandu, Nepal', 'NPR 45,000 - 70,000', 'data@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 30 DAY), 'Data Analysis, Python, SQL, Excel, Tableau, Pandas, Statistics', TRUE, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('Machine Learning Engineer', 'Build ML models and deploy them in production. Work with TensorFlow, PyTorch, and cloud platforms.', 'employment', 3, 'Remote', 'NPR 65,000 - 95,000', 'ml@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 30 DAY), 'Machine Learning, Python, TensorFlow, PyTorch, Data Science, SQL, AWS', TRUE, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('Data Science Intern', 'Internship for data science enthusiasts. Learn data analysis, machine learning, and data visualization techniques.', 'internship', 4, 'Lalitpur, Nepal', 'NPR 18,000 - 25,000', 'dataintern@nepaltech.com', DATE_ADD(NOW(), INTERVAL 50 DAY), 'Python, Data Analysis, Pandas, NumPy, Statistics, Excel', TRUE, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('Business Analyst', 'Bridge the gap between business and technology. Analyze requirements and create data-driven recommendations.', 'employment', 5, 'Kathmandu, Nepal', 'NPR 40,000 - 60,000', 'business@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 35 DAY), 'Data Analysis, Excel, SQL, Business Analysis, Project Management, Communication', TRUE, NOW()),
('Power BI Developer', 'Create interactive dashboards and reports using Power BI. Transform data into actionable business insights.', 'employment', 6, 'Pokhara, Nepal', 'NPR 42,000 - 65,000', 'powerbi@demo.org', DATE_ADD(NOW(), INTERVAL 30 DAY), 'Power BI, SQL, Data Analysis, Excel, Data Visualization, DAX', TRUE, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('Data Engineering Intern', 'Learn to build data pipelines and ETL processes. Work with big data technologies and cloud platforms.', 'internship', 3, 'Remote', 'NPR 16,000 - 24,000', 'dataeng@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 55 DAY), 'Python, SQL, Data Engineering, ETL, Git, Basic Programming', TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY)),

-- UI/UX Design Jobs (6)
('UI/UX Designer', 'Design beautiful and intuitive user interfaces for web and mobile applications. Create wireframes, prototypes, and design systems.', 'employment', 4, 'Kathmandu, Nepal', 'NPR 48,000 - 72,000', 'design@nepaltech.com', DATE_ADD(NOW(), INTERVAL 30 DAY), 'UI/UX Design, Figma, Adobe XD, User Research, Wireframing, Prototyping', TRUE, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('Graphic Designer', 'Create visual content for marketing materials, social media, and branding. Strong portfolio in graphic design required.', 'employment', 5, 'Lalitpur, Nepal', 'NPR 35,000 - 55,000', 'graphic@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 28 DAY), 'Photoshop, Illustrator, InDesign, Graphic Design, Branding, Creative Design', TRUE, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('UX Design Intern', 'Learn UX design principles and work on real projects. Create user flows, wireframes, and interactive prototypes.', 'internship', 6, 'Kathmandu, Nepal', 'NPR 14,000 - 22,000', 'uxintern@demo.org', DATE_ADD(NOW(), INTERVAL 50 DAY), 'UI/UX Design, Figma, User Research, Wireframing, Prototyping, Design Thinking', TRUE, NOW()),
('Product Designer', 'Design digital products from concept to launch. Collaborate with developers and product managers to create exceptional user experiences.', 'employment', 3, 'Remote', 'NPR 55,000 - 82,000', 'product@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 32 DAY), 'Product Design, UI/UX Design, Figma, User Research, Prototyping, Design Systems', TRUE, DATE_SUB(NOW(), INTERVAL 2 DAY)),
('Web Designer', 'Create responsive web designs using modern design tools. Translate designs into HTML/CSS when needed.', 'employment', 4, 'Pokhara, Nepal', 'NPR 38,000 - 58,000', 'webdesign@nepaltech.com', DATE_ADD(NOW(), INTERVAL 30 DAY), 'Web Design, HTML, CSS, Figma, Photoshop, Responsive Design, UI/UX Design', TRUE, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('Design Intern', 'Perfect starting point for design enthusiasts. Learn design principles and work on various design projects.', 'internship', 5, 'Kathmandu, Nepal', 'NPR 12,000 - 20,000', 'designintern@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 60 DAY), 'Graphic Design, Photoshop, Illustrator, Design Principles, Creative Thinking', TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY)),

-- DevOps & Cloud Jobs (4)
('DevOps Engineer', 'Manage infrastructure, CI/CD pipelines, and cloud deployments. Experience with Docker, Kubernetes, and AWS required.', 'employment', 3, 'Remote', 'NPR 60,000 - 90,000', 'devops@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 30 DAY), 'DevOps, Docker, Kubernetes, AWS, Jenkins, Linux, Git, CI/CD', TRUE, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('Cloud Engineer', 'Design and manage cloud infrastructure on AWS/Azure. Implement scalable and secure cloud solutions.', 'employment', 4, 'Kathmandu, Nepal', 'NPR 58,000 - 85,000', 'cloud@nepaltech.com', DATE_ADD(NOW(), INTERVAL 35 DAY), 'AWS, Azure, Cloud Computing, Linux, Docker, Terraform, Networking', TRUE, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('DevOps Intern', 'Learn DevOps practices including containerization, CI/CD, and cloud deployment. Work with modern DevOps tools.', 'internship', 6, 'Lalitpur, Nepal', 'NPR 18,000 - 26,000', 'devopsintern@demo.org', DATE_ADD(NOW(), INTERVAL 55 DAY), 'Linux, Git, Docker, Basic Programming, Cloud Computing, DevOps', TRUE, NOW()),
('Site Reliability Engineer', 'Ensure system reliability and performance. Monitor infrastructure and implement automation for scaling.', 'employment', 5, 'Remote', 'NPR 62,000 - 92,000', 'sre@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 32 DAY), 'DevOps, Kubernetes, AWS, Monitoring, Automation, Linux, Scripting', TRUE, DATE_SUB(NOW(), INTERVAL 2 DAY)),

-- Marketing & Content Jobs (6)
('Digital Marketing Specialist', 'Manage digital marketing campaigns across various platforms. Experience with SEO, SEM, and social media marketing required.', 'employment', 4, 'Kathmandu, Nepal', 'NPR 40,000 - 65,000', 'marketing@nepaltech.com', DATE_ADD(NOW(), INTERVAL 30 DAY), 'Digital Marketing, SEO, SEM, Social Media Marketing, Google Analytics, Content Marketing', TRUE, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('Content Writer', 'Create engaging content for blogs, websites, and social media. Strong writing skills and SEO knowledge preferred.', 'employment', 5, 'Remote', 'NPR 30,000 - 50,000', 'content@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 25 DAY), 'Content Writing, SEO, Copywriting, Research, Social Media, Blogging', TRUE, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('Social Media Manager Intern', 'Learn social media management and content creation. Help grow our social media presence across platforms.', 'internship', 6, 'Lalitpur, Nepal', 'NPR 12,000 - 20,000', 'social@demo.org', DATE_ADD(NOW(), INTERVAL 50 DAY), 'Social Media Marketing, Content Creation, Communication, Creativity', TRUE, NOW()),
('SEO Specialist', 'Optimize websites for search engines and improve organic rankings. Experience with keyword research and analytics required.', 'employment', 3, 'Kathmandu, Nepal', 'NPR 38,000 - 60,000', 'seo@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 28 DAY), 'SEO, Google Analytics, Keyword Research, Content Optimization, Link Building', TRUE, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('Marketing Intern', 'Gain hands-on experience in digital marketing. Work on campaigns, content creation, and market research.', 'internship', 4, 'Pokhara, Nepal', 'NPR 10,000 - 18,000', 'marketingintern@nepaltech.com', DATE_ADD(NOW(), INTERVAL 60 DAY), 'Marketing, Social Media, Communication, Creativity, Basic Analytics', TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY)),
('Content Marketing Manager', 'Develop and execute content marketing strategies. Manage content calendar and measure campaign performance.', 'employment', 5, 'Kathmandu, Nepal', 'NPR 45,000 - 70,000', 'contentmgr@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 35 DAY), 'Content Marketing, SEO, Social Media Marketing, Analytics, Strategy, Writing', TRUE, DATE_SUB(NOW(), INTERVAL 2 DAY)),

-- Testing & QA Jobs (3)
('QA Engineer', 'Ensure software quality through manual and automated testing. Experience with testing tools and methodologies required.', 'employment', 3, 'Kathmandu, Nepal', 'NPR 42,000 - 65,000', 'qa@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 30 DAY), 'Software Testing, Manual Testing, Automated Testing, Selenium, Bug Tracking, Quality Assurance', TRUE, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('Software Tester Intern', 'Learn software testing methodologies and tools. Work on test cases and bug reporting.', 'internship', 4, 'Lalitpur, Nepal', 'NPR 14,000 - 22,000', 'testintern@nepaltech.com', DATE_ADD(NOW(), INTERVAL 55 DAY), 'Software Testing, Manual Testing, Bug Tracking, Attention to Detail, Basic Programming', TRUE, NOW()),
('Test Automation Engineer', 'Develop and maintain automated test scripts. Experience with Selenium, Cypress, or similar tools required.', 'employment', 5, 'Remote', 'NPR 50,000 - 75,000', 'automation@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 32 DAY), 'Test Automation, Selenium, Python, JavaScript, CI/CD, Software Testing', TRUE, DATE_SUB(NOW(), INTERVAL 4 DAY)),

-- Project Management Jobs (3)
('Project Manager', 'Lead software development projects from inception to delivery. Strong communication and Agile/Scrum experience required.', 'employment', 3, 'Kathmandu, Nepal', 'NPR 55,000 - 85,000', 'pm@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 30 DAY), 'Project Management, Agile, Scrum, Communication, Leadership, Jira', TRUE, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('Scrum Master', 'Facilitate Agile ceremonies and help teams deliver high-quality software. Certified Scrum Master preferred.', 'employment', 4, 'Remote', 'NPR 52,000 - 78,000', 'scrum@nepaltech.com', DATE_ADD(NOW(), INTERVAL 35 DAY), 'Scrum, Agile, Project Management, Communication, Team Leadership, Jira', TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY)),
('Project Management Intern', 'Learn project management methodologies and tools. Assist in planning and tracking project progress.', 'internship', 6, 'Lalitpur, Nepal', 'NPR 15,000 - 24,000', 'pmintern@demo.org', DATE_ADD(NOW(), INTERVAL 50 DAY), 'Project Management, Communication, Organization, Microsoft Office, Teamwork', TRUE, DATE_SUB(NOW(), INTERVAL 3 DAY)),

-- Database & Backend Jobs (3)
('Database Administrator', 'Manage and optimize database systems. Experience with MySQL, PostgreSQL, or MongoDB required.', 'employment', 5, 'Kathmandu, Nepal', 'NPR 48,000 - 72,000', 'dba@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 30 DAY), 'MySQL, PostgreSQL, MongoDB, Database Administration, SQL, Performance Optimization', TRUE, DATE_SUB(NOW(), INTERVAL 4 DAY)),
('Backend Developer - Node.js', 'Build scalable backend services using Node.js and Express. Experience with RESTful APIs and microservices preferred.', 'employment', 3, 'Pokhara, Nepal', 'NPR 50,000 - 75,000', 'backend@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 28 DAY), 'Node.js, Express.js, MongoDB, REST API, Git, JavaScript, Microservices', TRUE, NOW()),
('Backend Development Intern', 'Learn backend development with Node.js or Python. Build APIs and work with databases.', 'internship', 4, 'Kathmandu, Nepal', 'NPR 16,000 - 24,000', 'backendintern@nepaltech.com', DATE_ADD(NOW(), INTERVAL 60 DAY), 'Node.js, Python, MySQL, REST API, Git, Basic Programming', TRUE, DATE_SUB(NOW(), INTERVAL 2 DAY)),

-- Miscellaneous Tech Jobs (3)
('System Administrator', 'Manage IT infrastructure and provide technical support. Experience with Linux, networking, and system administration required.', 'employment', 6, 'Kathmandu, Nepal', 'NPR 40,000 - 60,000', 'sysadmin@demo.org', DATE_ADD(NOW(), INTERVAL 30 DAY), 'Linux, System Administration, Networking, Troubleshooting, Bash Scripting, IT Support', TRUE, DATE_SUB(NOW(), INTERVAL 5 DAY)),
('Technical Writer', 'Create technical documentation, tutorials, and user guides. Strong writing skills and technical knowledge required.', 'employment', 5, 'Remote', 'NPR 35,000 - 55,000', 'techwrite@equalopportunity.edu', DATE_ADD(NOW(), INTERVAL 25 DAY), 'Technical Writing, Documentation, Communication, Technical Knowledge, Writing', TRUE, DATE_SUB(NOW(), INTERVAL 3 DAY)),
('IT Support Intern', 'Provide technical support to users and maintain IT systems. Learn troubleshooting and system administration.', 'internship', 3, 'Lalitpur, Nepal', 'NPR 12,000 - 20,000', 'itsupport@inclusivetech.com', DATE_ADD(NOW(), INTERVAL 55 DAY), 'IT Support, Troubleshooting, Communication, Basic Computer Skills, Help Desk', TRUE, DATE_SUB(NOW(), INTERVAL 1 DAY));

