-- Sample Job Opportunities for Avsar Nepal
-- This file contains 50 fake job posts for testing

USE avsar_db;

-- First, let's create some sample organizer accounts (if they don't exist)
-- These will be used as the organizer_id for the job posts
-- Note: Passwords are hashed with password_hash('password', PASSWORD_DEFAULT)

INSERT IGNORE INTO users (id, name, email, password, role, org_name, contact_person, phone) VALUES
(2, 'Tech Solutions Nepal', 'tech@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'organizer', 'Tech Solutions Nepal', 'Ramesh Shah', '+977-1-4444444'),
(3, 'Digital Innovations Pvt. Ltd.', 'digital@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'organizer', 'Digital Innovations Pvt. Ltd.', 'Sita Devi', '+977-1-5555555'),
(4, 'Creative Design Studio', 'creative@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'organizer', 'Creative Design Studio', 'Arjun Basnet', '+977-1-6666666'),
(5, 'Nepal Marketing Hub', 'marketing@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'organizer', 'Nepal Marketing Hub', 'Priya Thapa', '+977-1-7777777'),
(6, 'Finance Experts Ltd.', 'finance@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'organizer', 'Finance Experts Ltd.', 'Bikash Poudel', '+977-1-8888888'),
(7, 'Education First', 'education@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'organizer', 'Education First', 'Anita Gurung', '+977-1-9999999'),
(8, 'Startup Ventures', 'startup@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'organizer', 'Startup Ventures', 'Kiran Maharjan', '+977-1-1010101'),
(9, 'HR Solutions Nepal', 'hr@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'organizer', 'HR Solutions Nepal', 'Rajesh Tamang', '+977-1-2020202'),
(10, 'Global Tech Nepal', 'global@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'organizer', 'Global Tech Nepal', 'Maya Shrestha', '+977-1-3030303');

-- Now insert 50 job opportunities
-- Mix of employment and internship positions with varied locations and skills

INSERT INTO opportunities (organizer_id, title, description, requirements, type, location, is_active, views_count, date_posted) VALUES

-- Technology Jobs (1-15)
(2, 'Senior Full Stack Developer', 'We are looking for an experienced Full Stack Developer to join our growing tech team. You will be responsible for developing and maintaining web applications using modern technologies.', 'JavaScript, React, Node.js, MongoDB, PostgreSQL, REST API, Git, 3+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(2, 'Frontend Developer Intern', 'Perfect opportunity for students to learn React and modern frontend development. Work on real projects under mentorship of senior developers.', 'HTML, CSS, JavaScript, React basics, Git, Learning attitude', 'internship', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(3, 'Backend Developer', 'Join our backend team to build scalable and robust APIs. Work with microservices architecture and cloud technologies.', 'Python, Django, PostgreSQL, Redis, Docker, AWS, REST API, GraphQL', 'employment', 'Lalitpur', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(3, 'Mobile App Developer (React Native)', 'Develop cross-platform mobile applications for iOS and Android. Work with modern React Native framework and latest tools.', 'JavaScript, React Native, Redux, REST API, Firebase, 2+ years experience', 'employment', 'Pokhara', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(4, 'UI/UX Designer', 'Create beautiful and intuitive user interfaces. Work closely with developers to bring designs to life. Portfolio required.', 'Figma, Adobe XD, Photoshop, Illustrator, User Research, Wireframing, Prototyping', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(4, 'Graphic Design Intern', 'Learn professional graphic design while working on real client projects. Perfect for creative individuals starting their career.', 'Photoshop, Illustrator, Canva, Creativity, Basic design principles', 'internship', 'Biratnagar', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(2, 'DevOps Engineer', 'Manage our cloud infrastructure and CI/CD pipelines. Ensure smooth deployments and system reliability.', 'Docker, Kubernetes, AWS, Jenkins, Linux, Bash, Terraform, 2+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(3, 'Data Scientist', 'Apply machine learning algorithms to solve business problems. Work with large datasets and build predictive models.', 'Python, Machine Learning, TensorFlow, PyTorch, SQL, Data Analysis, Statistics, 3+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(5, 'PHP Developer', 'Develop and maintain web applications using PHP and Laravel framework. Work on exciting projects with a talented team.', 'PHP, Laravel, MySQL, JavaScript, Git, REST API, 2+ years experience', 'employment', 'Pokhara', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(5, 'WordPress Developer Intern', 'Learn WordPress development from experts. Create custom themes and plugins for clients.', 'HTML, CSS, JavaScript, PHP basics, WordPress, Eagerness to learn', 'internship', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(2, 'QA Engineer', 'Ensure quality of our software products through testing and automation. Work with testing frameworks and tools.', 'Manual Testing, Automated Testing, Selenium, JUnit, TestNG, Agile, 2+ years experience', 'employment', 'Lalitpur', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(3, 'Machine Learning Intern', 'Work on ML projects and learn from data science experts. Great opportunity for students interested in AI.', 'Python, Machine Learning basics, NumPy, Pandas, Scikit-learn, Mathematics', 'internship', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(4, 'Web Developer', 'Build responsive websites and web applications. Work with modern frameworks and technologies.', 'HTML, CSS, JavaScript, React, Vue.js, Node.js, MongoDB, 1+ years experience', 'employment', 'Biratnagar', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(5, 'Flutter Developer', 'Develop mobile applications using Flutter framework. Create beautiful and performant apps for iOS and Android.', 'Dart, Flutter, REST API, Firebase, Git, 1+ years experience', 'employment', 'Pokhara', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(2, 'Software Engineering Intern', 'Learn software engineering best practices. Work on real projects and gain valuable industry experience.', 'Programming basics, Data Structures, Algorithms, Problem Solving, Learning attitude', 'internship', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),

-- Marketing Jobs (16-25)
(5, 'Digital Marketing Manager', 'Lead our digital marketing efforts across all channels. Drive growth and engagement through strategic campaigns.', 'Digital Marketing, SEO, SEM, Social Media Marketing, Google Analytics, Content Marketing, 3+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(5, 'Social Media Marketing Intern', 'Manage social media accounts and create engaging content. Learn digital marketing strategies from experts.', 'Social Media, Content Creation, Canva, Communication Skills, Creativity', 'internship', 'Pokhara', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(7, 'Content Writer', 'Create compelling content for websites, blogs, and marketing materials. Excellent writing skills required.', 'Content Writing, SEO, Copywriting, Research Skills, English Proficiency, 2+ years experience', 'employment', 'Lalitpur', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(5, 'SEO Specialist', 'Optimize websites for search engines. Improve rankings and organic traffic through technical and content SEO.', 'SEO, Google Analytics, Keyword Research, Technical SEO, Content Optimization, 2+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(5, 'Marketing Intern', 'Learn various aspects of marketing including digital marketing, content creation, and campaign management.', 'Marketing basics, Communication Skills, Creativity, Social Media, Eagerness to learn', 'internship', 'Biratnagar', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(7, 'Brand Manager', 'Develop and execute brand strategies. Manage brand identity and ensure consistent messaging across channels.', 'Brand Management, Marketing Strategy, Communication, Creative Thinking, 3+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(5, 'Email Marketing Specialist', 'Create and execute email marketing campaigns. Analyze performance and optimize for better engagement.', 'Email Marketing, MailChimp, Campaign Management, Analytics, Copywriting, 1+ years experience', 'employment', 'Pokhara', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(5, 'Content Marketing Intern', 'Write blog posts, social media content, and marketing materials. Learn content strategy from experienced marketers.', 'Content Writing, Blogging, Social Media, Research Skills, Writing Skills', 'internship', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(7, 'Marketing Analyst', 'Analyze marketing data and provide insights to improve campaigns. Work with analytics tools and reporting.', 'Data Analysis, Google Analytics, Excel, Reporting, Marketing Metrics, 2+ years experience', 'employment', 'Lalitpur', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(5, 'Influencer Marketing Intern', 'Coordinate with influencers and manage partnerships. Learn about influencer marketing strategies.', 'Social Media, Communication Skills, Negotiation, Content Planning, Relationship Building', 'internship', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),

-- Finance Jobs (26-30)
(6, 'Financial Analyst', 'Analyze financial data and prepare reports. Support business decisions through financial insights.', 'Financial Analysis, Excel, Accounting, Financial Modeling, Analytical Skills, 2+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(6, 'Accounting Intern', 'Learn accounting practices and assist with financial record keeping. Great opportunity for accounting students.', 'Accounting basics, Excel, Attention to Detail, Math Skills, Learning attitude', 'internship', 'Pokhara', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(6, 'Finance Manager', 'Oversee financial operations and budgeting. Manage financial planning and reporting for the organization.', 'Financial Management, Budgeting, Financial Planning, Accounting, Leadership, 5+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(6, 'Tax Consultant', 'Provide tax consultation services to clients. Stay updated with tax laws and regulations.', 'Tax Planning, Tax Law, Accounting, Analytical Skills, Communication, 3+ years experience', 'employment', 'Lalitpur', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(6, 'Finance Intern', 'Assist with financial analysis and reporting. Learn finance fundamentals from experienced professionals.', 'Finance basics, Excel, Analytical Skills, Attention to Detail, Math Skills', 'internship', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),

-- Human Resources Jobs (31-35)
(9, 'HR Manager', 'Lead HR operations including recruitment, employee relations, and policy implementation. Build a great workplace culture.', 'HR Management, Recruitment, Employee Relations, Communication, Leadership, 4+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(9, 'HR Intern', 'Learn HR functions including recruitment, onboarding, and employee management. Perfect for HR students.', 'HR basics, Communication Skills, Organization Skills, Interpersonal Skills, Learning attitude', 'internship', 'Pokhara', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(9, 'Recruiter', 'Source and recruit top talent for various positions. Build relationships with candidates and hiring managers.', 'Recruitment, Sourcing, Interviewing, Communication, Relationship Building, 2+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(9, 'HR Assistant', 'Support HR operations including maintaining employee records, organizing events, and assisting with recruitment.', 'HR basics, Organization Skills, Communication, MS Office, Attention to Detail, 1+ years experience', 'employment', 'Lalitpur', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(9, 'Talent Acquisition Intern', 'Learn recruitment processes and assist with sourcing candidates. Great start for HR career.', 'Communication Skills, Research Skills, Organization, Interpersonal Skills, Learning attitude', 'internship', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),

-- Education Jobs (36-40)
(7, 'Online Instructor - Programming', 'Teach programming courses online. Share your expertise with eager learners and build your teaching portfolio.', 'Programming, Teaching, Communication Skills, Patience, Subject Expertise, 2+ years experience', 'employment', 'Remote', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(7, 'Teaching Assistant', 'Assist instructors with course delivery and student support. Perfect for students interested in education.', 'Subject Knowledge, Communication Skills, Patience, Organization Skills, Learning attitude', 'internship', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(7, 'Curriculum Developer', 'Design and develop educational content and curricula. Create engaging learning materials for students.', 'Curriculum Design, Content Development, Educational Technology, Research Skills, 3+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(7, 'E-Learning Content Creator', 'Create online learning materials including videos, quizzes, and interactive content. Work with e-learning platforms.', 'Content Creation, Video Editing, E-Learning Tools, Instructional Design, Creativity, 2+ years experience', 'employment', 'Pokhara', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(7, 'Education Intern', 'Learn about educational program development and delivery. Assist with various educational initiatives.', 'Education basics, Communication Skills, Content Creation, Organization Skills, Learning attitude', 'internship', 'Lalitpur', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),

-- Business & Sales Jobs (41-45)
(8, 'Business Development Manager', 'Drive business growth through partnerships and client acquisition. Build relationships and expand market reach.', 'Business Development, Sales, Networking, Communication, Negotiation, 3+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(8, 'Sales Intern', 'Learn sales techniques and assist with business development activities. Great opportunity for business students.', 'Communication Skills, Negotiation, Customer Service, Learning attitude, Persistence', 'internship', 'Pokhara', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(8, 'Account Manager', 'Manage client relationships and ensure customer satisfaction. Drive account growth and retention.', 'Account Management, Client Relations, Communication, Problem Solving, 2+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(8, 'Sales Representative', 'Generate leads and convert prospects into customers. Meet sales targets and build customer relationships.', 'Sales, Communication, Customer Service, Persistence, Negotiation, 1+ years experience', 'employment', 'Biratnagar', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(8, 'Business Development Intern', 'Learn business development strategies and assist with market research. Perfect for business students.', 'Business basics, Research Skills, Communication, Networking, Learning attitude', 'internship', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),

-- More Tech Jobs (46-50)
(10, 'Cloud Engineer', 'Design and manage cloud infrastructure on AWS/Azure. Ensure scalability and reliability of cloud services.', 'AWS, Azure, Cloud Architecture, Docker, Kubernetes, Linux, 3+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(10, 'Database Administrator', 'Manage and optimize database systems. Ensure data security, performance, and availability.', 'MySQL, PostgreSQL, MongoDB, Database Design, SQL, Performance Tuning, 3+ years experience', 'employment', 'Lalitpur', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(2, 'System Administrator', 'Maintain and manage IT infrastructure. Ensure system security and optimal performance.', 'Linux, Windows Server, Networking, System Security, Troubleshooting, 2+ years experience', 'employment', 'Pokhara', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(3, 'Blockchain Developer', 'Develop blockchain applications and smart contracts. Work with cutting-edge blockchain technology.', 'Blockchain, Solidity, Ethereum, Smart Contracts, Web3, JavaScript, 2+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY)),
(10, 'Cybersecurity Analyst', 'Protect systems and networks from security threats. Monitor security incidents and implement safeguards.', 'Cybersecurity, Network Security, Security Tools, Incident Response, Risk Assessment, 2+ years experience', 'employment', 'Kathmandu', TRUE, FLOOR(RAND() * 100), DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 30) DAY));

-- Note: The organizer_id values (2-10) should correspond to existing users with role 'organizer'
-- If these users don't exist, you may need to adjust the IDs or create the organizer users first
-- The password hash for all sample organizers is 'password' (hashed using PHP password_hash function)

